syntax on
set tabstop=4
set sw=4
set expandtab
set number
set cursorline
set cuc
set cc=80

fu! CurrentFile()
    let file=expand("%:p")
    if file==""
        echom "Not editing a file :("
    else
        echom file
    endif
endfunction

fu! List()
    !ls ./
endfunction

fu! VolumeUp(amt)
    !ncmpcpp volume +a:amt
endfunction 

fu! VolumeDown()
    !ncmpcpp volume -5
endfunction

fu! Play()
    !ncmpcpp play
endfunction

fu! Pause()
    !ncmpcpp pause
endfunction

nnoremap <expr> <c-v>f CurrentFile()

nnoremap <expr> <c-v>l List()

nnoremap <expr> <c-v>+ VolumeUp()
nnoremap <expr> <c-v>- VolumeDown()
nnoremap <expr> <c-v>pl Play()
nnoremap <expr> <c-v>pa Pause()
