syntax on
set tabstop=4
set sw=4
set expandtab
set number
set cursorline
set cuc
set cc=80
set background=dark

fu! CurrentFile()
    let file=expand("%:p")
    if file==""
        echom "Not editing a file :("
    else
        echom file
    endif
endfunction

fu! List()
    !ls ./
endfunction

nnoremap <expr> <c-v>f CurrentFile()

nnoremap <expr> <c-v>l List()
